### PR TITLE
Add openjdk7 to test out https://freenet.mantishub.io/view.php?id=7023

### PR DESCRIPTION
**Pull request by desyncr**

### CODE REVIEW

**Comment by ArneBab** [comment]
Did you already test using a static member and passing that to the getInstance? 

```
+++ b/src/freenet/crypt/KeyGenUtils.java
@@ -36,9 +36,7 @@ import freenet.support.Fields;
  */
 public final class KeyGenUtils {
 
-    static {
-        java.security.Security.insertProviderAt(new BouncyCastleProvider(), 1);
-    }
+    private static BouncyCastleProvider bcProvider = new BouncyCastleProvider();
 
     /**
      * Generates a public/private key pair formatted for the algorithm specified
@@ -51,7 +49,7 @@ public final class KeyGenUtils {
             throw new UnsupportedTypeException(type);
         }
         try {
-            KeyPairGenerator kg = KeyPairGenerator.getInstance(type.alg);
+            KeyPairGenerator kg = KeyPairGenerator.getInstance(type.alg, bcProvider);
...
```

**Comment by desyncr** [comment]
No I haven't. I'm gonna start over from `freenet-bc-patch` branch.

**Comment by ArneBab** [comment]
I tried re-using the instance. See https://github.com/freenet/fred/pull/642

**Comment by desyncr** [comment]
I'm gonna try out this branch locally. The setup is the one I mentioned at https://github.com/freenet/fred/pull/640.

**Comment by desyncr** [comment]
@ArneBab I don't think abad64d133ed9a674d5f666f48db178a85652b9e actually fixes the issues with openjdk7. I ran `test-bc-openjdk7` with no changes (from `master`) with openjdk7 and still fails. Can you confirm?

**Comment by ArneBab** [comment]
abad64d fixes the tests on my setup.

**Comment by ArneBab** [comment]
Could you test whether the tests succeed if you just run https://github.com/freenet/fred/pull/642 ?

**Comment by desyncr** [comment]
@ArneBab 
```
freenet.store.saltedhash.SaltedHashSlotFilterTest > testCHKDelayedTurnOnSlotFiltersWithCleaner FAILED
    junit.framework.AssertionFailedError at SaltedHashSlotFilterTest.java:295

freenet.store.caching.CachingFreenetStoreTest > testOnCloseCHK FAILED
    java.lang.NullPointerException at CachingFreenetStoreTest.java:584

freenet.store.RAMSaltMigrationTest > testSaltedStoreOldBlock FAILED
    java.lang.NullPointerException at RAMSaltMigrationTest.java:414

freenet.store.RAMSaltMigrationTest > testSaltedStoreResize FAILED
    java.lang.AssertionError at RAMSaltMigrationTest.java:332
Shutting down...

**Comment by desyncr** [comment]
@ArneBab It fails on that branch :(

```
freenet.store.saltedhash.SaltedHashSlotFilterTest > testCHKDelayedTurnOnSlotFiltersWithCleaner FAILED
    junit.framework.AssertionFailedError at SaltedHashSlotFilterTest.java:295

freenet.store.caching.CachingFreenetStoreTest > testOnCloseCHK FAILED
    java.lang.NullPointerException at CachingFreenetStoreTest.java:584

freenet.store.RAMSaltMigrationTest > testSaltedStoreOldBlock FAILED
    java.lang.NullPointerException at RAMSaltMigrationTest.java:414

freenet.store.RAMSaltMigrationTest > testSaltedStoreResize FAILED
    java.lang.AssertionError at RAMSaltMigrationTest.java:332
Shutting down...
```

I'm testing with openjdk8 to check if it's my setup the issue.

**Comment by ArneBab** [comment]
That’s a different error, right?

**Comment by desyncr** [comment]
Probably my setup:

```
$ docker run -it -v gradle-cache:/tmp/.gradle -v "$PWD":/home/gradle/project -w /home/gradle/project  gradle:jdk8 gradle test

...

> Task :test

freenet.store.saltedhash.SaltedHashSlotFilterTest > testCHKDelayedTurnOnSlotFiltersWithCleaner FAILED
    junit.framework.AssertionFailedError at SaltedHashSlotFilterTest.java:295

freenet.store.saltedhash.SaltedHashSlotFilterTest > testCHKDelayedTurnOnSlotFilters FAILED
    java.lang.NullPointerException at SaltedHashSlotFilterTest.java:305

freenet.store.RAMSaltMigrationTest > testSaltedStoreWithClose FAILED
    java.lang.NullPointerException at RAMSaltMigrationTest.java:414

freenet.store.RAMSaltMigrationTest > testSaltedStoreResize FAILED
    java.lang.AssertionError at RAMSaltMigrationTest.java:348

...
```

**Comment by ArneBab** [comment]
Is that due to docker?

**Comment by ArneBab** [comment]
The failures at https://travis-ci.org/desyncr/fred/jobs/439843799 are the failures which should be fixed (and now work for me).

**Comment by ArneBab** [comment]
I’m running java version "1.7.0_181" — could there be a difference?

There isn’t any freenet package in the backtrace. Could this be gradle which fails?

**Comment by ArneBab** [comment]
https://stackoverflow.com/questions/47789963/how-to-avoid-ec-parameters-error-using-the-openjdk7-docker-image-and-a-gradle

could this be relevant to your test?

**Comment by ArneBab** [comment]
https://github.com/fastlane/fastlane/issues/10461

**Comment by desyncr** [comment]
Yeah, I'm discarding this docker setup. Now I'll try with the workaround at https://github.com/eseifert/gral/commit/c24e08a91952a99b8c8b686a1b172335db8cdf87

**Comment by desyncr** [comment]
I'm concluding that due to a Travis-ci setup it may not be possible to run against openjdk, which is a pity.
Nevertheless it should not delay 1481 release any further as I'm running on https://github.com/freenet/fred/pull/642 and so far I see no OOM errors nor restarts.

**Comment by ArneBab** [comment]
Thank you!

I’m now preparing a final test release, going to a testing update key. If that is successful, I only have to switch to the real insert key and we finally have 1481.

**Comment by desyncr** [comment]
I believe it's safe to run tests against openjdk7, oraclejdk7, oraclejdk8, oraclejdk9.

**Comment by ArneBab** [comment]
(though actually inserting will have to wait for tomorrow — I need to sleep and tomorrow is a long working day)

**Comment by desyncr** [comment]
I'm killing off this PR. So far we know:

- There're issues with `openjdk7` and `oraclejdk7` on TravisCI
- We've no easy way to setup multiple environments locally (ie, docker. I'm looking into it)
- Memory issue was fixed with https://github.com/freenet/fred/pull/642

Release 1481 should be good to go! 🎉

**Pull request closed without merging**
